// SPDX-FileCopyrightText: 2026 Meddle S.r.l.
// SPDX-License-Identifier: Apache-2.0

// Turns the hand-written contract sources into the committed TypeScript under
// `src/generated/` (docs/architecture.md#contracts):
//
//   schemas/v1/*.schema.json  ->  generated/schemas.ts, generated/types.ts, generated/validators.ts
//   topics.json               ->  generated/topics.ts
//   embedding.json (optional) ->  generated/embedding.ts
//
// Run it with `pnpm --filter @fdp/contracts generate`. The output is deterministic — object
// keys are sorted, lines end with LF and every file ends with a newline — so `check-drift`
// can prove the committed files still match their sources.
//
// `--out <dir>` writes somewhere else than `src/generated`; `test/generate.test.ts` uses it to
// reproduce the committed files in a temporary directory.

import _Ajv2020 from "ajv/dist/2020.js";
import type { AnySchemaObject } from "ajv";
import _addFormats from "ajv-formats";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

// ajv and ajv-formats ship CommonJS with a default export, which Node's ESM interop hands
// back as the module object itself. The casts restore the declared class and plugin types.
const Ajv2020 = _Ajv2020 as unknown as typeof _Ajv2020.default;
const addFormats = _addFormats as unknown as typeof _addFormats.default;

const PACKAGE_ROOT = resolve(import.meta.dirname, "..");
const SCHEMA_DIR = join(PACKAGE_ROOT, "schemas", "v1");
const TOPICS_FILE = join(PACKAGE_ROOT, "topics.json");
const EMBEDDING_FILE = join(PACKAGE_ROOT, "embedding.json");

/**
 * The Ajv options every validator in this repository uses.
 *
 * `allowUnionTypes` is needed by `common.schema.json#/$defs/sample_value`, the one definition
 * that is legitimately `["number", "boolean"]`: a telemetry value is a number for an analog tag
 * and a boolean for a digital one. Every other strict-mode check stays on.
 */
const AJV_OPTIONS = { strict: true, allErrors: false, allowUnionTypes: true } as const;

// The header every generated file starts with. The tags below belong to those files, not to
// this one, so they are fenced off: `reuse lint` would otherwise read the closing quote as part
// of the expression and report this script as non-compliant.
// REUSE-IgnoreStart
const BANNER = [
  "// Code generated by `pnpm --filter @fdp/contracts generate`. DO NOT EDIT.",
  "// Sources: packages/contracts/schemas/v1/*.schema.json, topics.json, embedding.json",
  "// SPDX-FileCopyrightText: 2026 Meddle S.r.l.",
  "// SPDX-License-Identifier: Apache-2.0",
].join("\n");
// REUSE-IgnoreEnd

interface SchemaFile {
  /** File stem, e.g. `alert-system`. */
  readonly name: string;
  /** `urn:fdp:schema:<name>:v1`. */
  readonly id: string;
  readonly schema: AnySchemaObject;
}

interface TopicEntry {
  readonly template: string;
  readonly schema: string;
  readonly qos: number;
  readonly retain: boolean;
  readonly publisher: string;
}

interface TopicTable {
  readonly roots: Record<string, string>;
  readonly default_unit_id: string;
  readonly topics: Record<string, TopicEntry>;
  readonly acl: Record<string, { readonly read: string[]; readonly write: string[] }>;
}

/** Recursively sorts object keys so the emitted literals do not depend on authoring order. */
function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value === null || typeof value !== "object") return value;
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(value as Record<string, unknown>).sort()) {
    sorted[key] = sortKeys((value as Record<string, unknown>)[key]);
  }
  return sorted;
}

/**
 * Drops every explicit `additionalProperties: true`.
 *
 * The envelope and every message that extends it keep top-level unknown fields legal, but
 * `json-schema-to-typescript` turns that into an `[k: string]: unknown` index signature, which
 * would make a misspelled field type-check.
 * Validation still accepts unknown fields; only the generated types are closed.
 */
function dropOpenObjects(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(dropOpenObjects);
  if (value === null || typeof value !== "object") return value;
  const out: Record<string, unknown> = {};
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    if (key === "additionalProperties" && child === true) continue;
    out[key] = dropOpenObjects(child);
  }
  return out;
}

/**
 * Rewrites draft 2020-12 `prefixItems` into the draft-07 tuple form `items: [...]`.
 *
 * `json-schema-to-typescript` 16 does not read `prefixItems`, so a tuple such as the
 * `[iso_ts, number | null]` point of `api-telemetry-series` would become `[unknown, unknown]`.
 * Ajv 2020 rejects the draft-07 form (`data/items must be object,boolean`), so the sources keep
 * `prefixItems` and only the copies handed to the type generator are rewritten.
 * `minItems`/`maxItems` already pin the length in both forms.
 */
function tupleItems(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(tupleItems);
  if (value === null || typeof value !== "object") return value;
  const out: Record<string, unknown> = {};
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    out[key === "prefixItems" && Array.isArray(child) ? "items" : key] = tupleItems(child);
  }
  return out;
}

function readJson(file: string): unknown {
  return JSON.parse(readFileSync(file, "utf8")) as unknown;
}

/**
 * Every schema of `schemas/v1`, ordered by file stem.
 *
 * The stems are sorted, not the file names: `catalog-entry.schema.json` sorts before
 * `catalog.schema.json` because `-` precedes `.`, while `src/testing.ts` `listSchemaNames()`
 * sorts `catalog` before `catalog-entry`. Sorting the same way keeps `SCHEMA_NAMES` equal to
 * what a consumer reads from disk whenever one stem is a prefix of another.
 */
function loadSchemas(): SchemaFile[] {
  const names = readdirSync(SCHEMA_DIR)
    .filter((f) => f.endsWith(".schema.json"))
    .map((file) => basename(file, ".schema.json"))
    .sort();
  return names.map((name) => {
    const file = `${name}.schema.json`;
    const schema = readJson(join(SCHEMA_DIR, file)) as AnySchemaObject;
    const id = `urn:fdp:schema:${name}:v1`;
    if (schema.$id !== id) {
      throw new Error(`${file}: $id is ${String(schema.$id)}, expected ${id}`);
    }
    return { name, id, schema };
  });
}

/** Compiles every schema once, so a broken schema fails the generator and not a consumer. */
function checkSchemas(schemaFiles: SchemaFile[]): void {
  const ajv = new Ajv2020({ ...AJV_OPTIONS });
  addFormats(ajv);
  for (const { schema } of schemaFiles) ajv.addSchema(schema);
  for (const { name, id } of schemaFiles) {
    if (ajv.getSchema(id) === undefined) throw new Error(`${name}: ${id} did not compile`);
  }
}

function jsonLiteral(value: unknown, indent: number): string {
  return JSON.stringify(sortKeys(value), null, 2)
    .split("\n")
    .join("\n" + " ".repeat(indent));
}

function renderSchemas(schemaFiles: SchemaFile[]): string {
  const entries = schemaFiles
    .map(({ name, schema }) => `  ${JSON.stringify(name)}: ${jsonLiteral(schema, 2)},`)
    .join("\n");
  const ids = schemaFiles
    .map(({ name, id }) => `  ${JSON.stringify(name)}: ${JSON.stringify(id)},`)
    .join("\n");
  const names = schemaFiles.map(({ name }) => `  ${JSON.stringify(name)},`).join("\n");
  return `${BANNER}

/** Every schema of \`schemas/v1\`, keyed by file stem, embedded so that \`dist/\` is self-contained. */
export const schemas = {
${entries}
} as const;

/** The schema names in file-stem order. \`common\` holds only \`$defs\` and is never a message. */
export const SCHEMA_NAMES = [
${names}
] as const;

export type SchemaName = (typeof SCHEMA_NAMES)[number];

/** The \`$id\` of every schema; a message repeats it in its \`schema\` field. */
export const SCHEMA_IDS = {
${ids}
} as const satisfies Record<SchemaName, \`urn:fdp:schema:\${string}:v\${number}\`>;
`;
}

async function renderTypes(schemaFiles: SchemaFile[]): Promise<string> {
  const prepared = new Map(
    schemaFiles.map(({ id, schema }) => [
      id,
      tupleItems(dropOpenObjects(schema)) as AnySchemaObject,
    ]),
  );
  const messages = schemaFiles.filter(({ name }) => name !== "common");
  const root = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    // Not `urn:fdp:schema:…`, so the resolver below is never asked to read this wrapper.
    $id: "urn:fdp:contracts:schema-type-map",
    title: "SchemaTypeMap",
    description: "Maps every message schema name to the TypeScript type of its payload.",
    type: "object",
    properties: Object.fromEntries(messages.map(({ name, id }) => [name, { $ref: id }])),
    required: messages.map(({ name }) => name),
  };
  const body = await compile(root as never, "SchemaTypeMap", {
    additionalProperties: false,
    bannerComment: "",
    declareExternallyReferenced: true,
    unknownAny: true,
    format: true,
    style: {
      parser: "typescript",
      printWidth: 100,
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
      useTabs: false,
    },
    $refOptions: {
      resolve: {
        // Contract schemas reference each other by URN, not by path, so $RefParser needs a
        // resolver that maps `urn:fdp:schema:<name>:v1` back to the file it was read from.
        fdp: {
          order: 1,
          canRead: /^urn:fdp:schema:/,
          read: (file: { url: string }) => {
            const schema = prepared.get(file.url);
            if (schema === undefined) throw new Error(`unknown schema reference ${file.url}`);
            return JSON.stringify(schema);
          },
        },
      },
    },
  });
  return `${BANNER}\n\n${body.trimEnd()}\n`;
}

function renderValidators(): string {
  return `${BANNER}

import type { AnySchemaObject, ValidateFunction } from "ajv";
import _Ajv2020 from "ajv/dist/2020.js";
import _addFormats from "ajv-formats";

import { SCHEMA_IDS, SCHEMA_NAMES, schemas } from "./schemas.ts";
import type { SchemaName } from "./schemas.ts";

export type { SchemaName } from "./schemas.ts";

// ajv and ajv-formats ship CommonJS with a default export, which Node's ESM interop hands
// back as the module object itself. The casts restore the declared class and plugin types.
const Ajv2020 = _Ajv2020 as unknown as typeof _Ajv2020.default;
const addFormats = _addFormats as unknown as typeof _addFormats.default;

/**
 * The Ajv options every validator in this repository uses.
 *
 * \`allowUnionTypes\` is needed by \`common.schema.json#/$defs/sample_value\`, the one definition
 * that is legitimately \`["number", "boolean"]\`: a telemetry value is a number for an analog tag
 * and a boolean for a digital one. Every other strict-mode check stays on.
 */
export const AJV_OPTIONS = { strict: true, allErrors: false, allowUnionTypes: true } as const;

const ajv = new Ajv2020({ ...AJV_OPTIONS });
addFormats(ajv);

for (const name of SCHEMA_NAMES) {
  ajv.addSchema(schemas[name] as unknown as AnySchemaObject);
}

function compileAll(): Record<SchemaName, ValidateFunction> {
  const compiled: Partial<Record<SchemaName, ValidateFunction>> = {};
  for (const name of SCHEMA_NAMES) {
    const validate = ajv.getSchema(SCHEMA_IDS[name]);
    if (validate === undefined) {
      throw new Error(\`@fdp/contracts: \${name} (\${SCHEMA_IDS[name]}) did not compile\`);
    }
    compiled[name] = validate;
  }
  return compiled as Record<SchemaName, ValidateFunction>;
}

/** One compiled validator per schema, built once when this module loads. */
export const validators: Record<SchemaName, ValidateFunction> = compileAll();

/** Narrows an arbitrary string to a known schema name. */
export function isSchemaName(name: string): name is SchemaName {
  return (SCHEMA_NAMES as readonly string[]).includes(name);
}
`;
}

/** `telemetry_samples` -> `telemetrySamples`. */
function camelCase(key: string): string {
  return key.replace(/_([a-z0-9])/g, (_match, char: string) => char.toUpperCase());
}

function escapeRegExp(literal: string): string {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** A topic template as an anchored pattern, with `{unit_id}` matching one MQTT level. */
function templatePattern(template: string): string {
  return `^${template.split("{unit_id}").map(escapeRegExp).join("[^/+#]+")}$`;
}

/** A topic template as a template literal, with `{unit_id}` replaced by the argument. */
function templateLiteral(template: string): string {
  return `\`${template.split("{unit_id}").join("${unitId}")}\``;
}

function renderTopics(table: TopicTable): string {
  const keys = Object.keys(table.topics);
  const unknownRoots = keys.filter((key) => {
    const root = (table.topics[key] as TopicEntry).template.split("/")[0];
    return root === undefined || !Object.values(table.roots).includes(root);
  });
  if (unknownRoots.length > 0) {
    throw new Error(`topics.json: templates without a declared root: ${unknownRoots.join(", ")}`);
  }

  const builders = keys
    .map((key) => {
      const entry = table.topics[key] as TopicEntry;
      return `  ${camelCase(key)}: (unitId: string = DEFAULT_UNIT_ID): string =>\n    ${templateLiteral(entry.template)},`;
    })
    .join("\n");

  const meta = keys
    .map((key) => {
      const entry = table.topics[key] as TopicEntry;
      return `  ${camelCase(key)}: ${jsonLiteral({ key, ...entry }, 2)},`;
    })
    .join("\n");

  const acl = Object.keys(table.acl)
    .map((credential) => {
      const value = table.acl[credential] as { read: string[]; write: string[] };
      return `  ${JSON.stringify(credential)}: ${jsonLiteral({ read: value.read, write: value.write }, 2)},`;
    })
    .join("\n");

  const patterns = keys
    .map((key) => {
      const entry = table.topics[key] as TopicEntry;
      return `  [new RegExp(${JSON.stringify(templatePattern(entry.template))}), ${JSON.stringify(entry.schema)}],`;
    })
    .join("\n");

  return `${BANNER}

import { SCHEMA_NAMES } from "./schemas.ts";
import type { SchemaName } from "./schemas.ts";

/** The only unit of this proof of concept. */
export const DEFAULT_UNIT_ID = ${JSON.stringify(table.default_unit_id)};

/** The two top-level roots of the topic tree. */
export const ROOTS = ${jsonLiteral(table.roots, 0)} as const;

/** One builder per topic; each takes the unit id and returns the concrete topic string. */
export const topics = {
${builders}
};

/** QoS, retain flag, payload schema and publisher of every topic. */
export const TOPIC_META = {
${meta}
} as const;

export type TopicKey = keyof typeof TOPIC_META;

/**
 * Read and write filters per broker credential.
 *
 * This is what \`infra/mosquitto/acl\` is rendered from and diffed against.
 */
export const ACL = {
${acl}
} as const;

export type AclCredential = keyof typeof ACL;

/** The topic filters a credential may subscribe to, with the unit id substituted. */
export function subscriptionsFor(
  credential: AclCredential,
  unitId: string = DEFAULT_UNIT_ID,
): string[] {
  return ACL[credential].read.map((filter) => filter.split("{unit_id}").join(unitId));
}

const TOPIC_PATTERNS: ReadonlyArray<readonly [RegExp, string]> = [
${patterns}
];

const KNOWN_SCHEMAS: ReadonlySet<string> = new Set(SCHEMA_NAMES);

/**
 * The schema a payload on \`topic\` must validate against.
 *
 * Returns \`undefined\` for a topic no template matches, and for a topic whose schema has not
 * been written yet.
 */
export function schemaForTopic(topic: string): SchemaName | undefined {
  for (const [pattern, schema] of TOPIC_PATTERNS) {
    if (pattern.test(topic)) {
      return KNOWN_SCHEMAS.has(schema) ? (schema as SchemaName) : undefined;
    }
  }
  return undefined;
}
`;
}

function renderEmbedding(): string {
  if (!existsSync(EMBEDDING_FILE)) {
    return `${BANNER}

/**
 * The embedding model pin.
 *
 * \`null\` while \`packages/contracts/embedding.json\` is absent; the generator embeds the file
 * as a frozen literal as soon as it exists.
 */
export const EMBEDDING = null;
`;
  }
  return `${BANNER}

/** The embedding model pin, embedded from \`packages/contracts/embedding.json\`. */
export const EMBEDDING = ${jsonLiteral(readJson(EMBEDDING_FILE), 0)} as const;
`;
}

function write(outDir: string, file: string, contents: string): void {
  const normalised = contents.replace(/\r\n/g, "\n");
  writeFileSync(join(outDir, file), normalised.endsWith("\n") ? normalised : `${normalised}\n`);
}

function outDirFromArgv(argv: readonly string[]): string {
  const flag = argv.indexOf("--out");
  if (flag === -1) return join(PACKAGE_ROOT, "src", "generated");
  const value = argv[flag + 1];
  if (value === undefined) throw new Error("--out needs a directory");
  return resolve(value);
}

export async function generate(outDir: string): Promise<string[]> {
  mkdirSync(outDir, { recursive: true });
  const schemaFiles = loadSchemas();
  checkSchemas(schemaFiles);
  const table = readJson(TOPICS_FILE) as TopicTable;

  write(outDir, "schemas.ts", renderSchemas(schemaFiles));
  write(outDir, "types.ts", await renderTypes(schemaFiles));
  write(outDir, "validators.ts", renderValidators());
  write(outDir, "topics.ts", renderTopics(table));
  write(outDir, "embedding.ts", renderEmbedding());

  return ["schemas.ts", "types.ts", "validators.ts", "topics.ts", "embedding.ts"];
}

if (process.argv[1] !== undefined && import.meta.filename === resolve(process.argv[1])) {
  const outDir = outDirFromArgv(process.argv.slice(2));
  const written = await generate(outDir);
  process.stdout.write(`@fdp/contracts: wrote ${written.length} files to ${outDir}\n`);
}
