// SPDX-FileCopyrightText: 2026 Meddle S.r.l.
// SPDX-License-Identifier: Apache-2.0

package testutil

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

const (
	// MosquittoImage is the broker image, pinned like every other image of the
	// project.
	MosquittoImage = "eclipse-mosquitto:2.0.22"
	// MosquittoDirEnv overrides where the committed broker configuration
	// lives.
	MosquittoDirEnv = "FDP_MOSQUITTO_DIR"
	// DefaultMosquittoDir is infra/mosquitto seen from a package under
	// services/modbus/internal, which is four levels below the repository
	// root.
	DefaultMosquittoDir = "../../../../infra/mosquitto"
	// MosquittoPort is the container port the broker listens on.
	MosquittoPort = "1883/tcp"

	// containerConfigDir is where mosquitto.conf names its own files.
	containerConfigDir = "/mosquitto/config"
	// containerEntrypoint is where the committed entrypoint is copied; it
	// renders the password file and then hands over to the image's own
	// entrypoint (infra/mosquitto/entrypoint.sh).
	containerEntrypoint = "/fdp-entrypoint.sh"
	// startupTimeout bounds pulling and starting the broker.
	startupTimeout = 2 * time.Minute
	// stopTimeout is how long the broker is given to shut down before Docker
	// kills it.
	stopTimeout = 5 * time.Second
)

// minimalConfig is the fallback used when the committed configuration is not
// in the checkout: an anonymous broker with no ACL, enough for a round trip
// but not for the isolation assertions.
const minimalConfig = `# SPDX-FileCopyrightText: 2026 Meddle S.r.l.
# SPDX-License-Identifier: Apache-2.0
# Generated by services/modbus/internal/testutil for a checkout without
# infra/mosquitto. It has no credentials and no ACL on purpose.
listener 1883 0.0.0.0
protocol mqtt
allow_anonymous true
persistence false
retain_available true
log_dest stdout
log_type notice
`

// MosquittoConfigDir returns the committed broker configuration directory and
// whether it is in the checkout. A test that asserts the ACL calls this first
// and skips those assertions when it reports false.
func MosquittoConfigDir() (string, bool) {
	dir := os.Getenv(MosquittoDirEnv)
	if dir == "" {
		dir = DefaultMosquittoDir
	}
	abs, err := filepath.Abs(dir)
	if err != nil {
		return "", false
	}
	// mosquitto.conf names the other two files, so it is the one that decides
	// whether this directory is usable.
	if _, err := os.Stat(filepath.Join(abs, "mosquitto.conf")); err != nil {
		return "", false
	}
	return abs, true
}

// MosquittoPassword returns the password for a broker credential: the
// MQTT_<USER>_PASSWORD environment variable when it is set, else the committed
// PoC default from infra/mosquitto/passwd.txt. `-` becomes `_` in the variable
// name, so backend-diag reads MQTT_BACKEND_DIAG_PASSWORD.
//
// These are not secrets: they are committed defaults for a demo broker whose
// ACL is an isolation boundary, not a security control.
func MosquittoPassword(t testing.TB, user string) string {
	t.Helper()

	variable := "MQTT_" + strings.ToUpper(strings.ReplaceAll(user, "-", "_")) + "_PASSWORD"
	if value := os.Getenv(variable); value != "" {
		return value
	}

	dir, ok := MosquittoConfigDir()
	if !ok {
		t.Fatalf("testutil: no %s and no infra/mosquitto to read the default for %q from", variable, user)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "passwd.txt"))
	if err != nil {
		t.Fatalf("testutil: reading the committed broker passwords: %v", err)
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, password, found := strings.Cut(line, ":")
		if found && name == user {
			return password
		}
	}
	t.Fatalf("testutil: no credential %q in %s/passwd.txt", user, dir)
	return ""
}

// StartMosquitto runs the pinned Mosquitto image on a random host port and
// returns its URL and the configuration directory it was started from.
//
// With infra/mosquitto in the checkout the container runs the committed
// configuration, ACL and entrypoint, so it enforces exactly the credentials
// the compose stack does; cfgDir is then that directory. Otherwise a minimal
// anonymous configuration is generated into a temporary directory and cfgDir
// names that instead — use MosquittoConfigDir to tell the two apart before
// asserting on the ACL.
//
// The test skips when no Docker daemon answers. The container stops in
// t.Cleanup.
func StartMosquitto(t testing.TB) (url string, cfgDir string) {
	t.Helper()

	broker := StartMosquittoContainer(t)
	return broker.URL, broker.ConfigDir
}

// MosquittoContainer is a running broker together with the handle a test needs
// to stop it and bring it back (scenario E).
//
// Docker republishes the mapped port when a container starts again, so URL
// changes across a restart. A caller whose clients must keep one address in
// front of the broker puts its own forwarder there and re-points it at
// Address after every Start.
type MosquittoContainer struct {
	// Container is the running broker.
	Container testcontainers.Container
	// URL is the broker URL as it stands.
	URL string
	// ConfigDir is the directory the configuration was taken from, as
	// StartMosquitto describes it.
	ConfigDir string
}

// StartMosquittoContainer is StartMosquitto with the container handle.
func StartMosquittoContainer(t testing.TB) *MosquittoContainer {
	t.Helper()
	requireDocker(t)

	ctx := context.Background()
	cfgDir, files := mosquittoFiles(t)

	options := []testcontainers.ContainerCustomizer{
		testcontainers.WithName("fdp-sim-mqtt-" + randomSuffix(t)),
		testcontainers.WithExposedPorts(MosquittoPort),
		testcontainers.WithFiles(files...),
		// Readiness is the listening port, not a log line: the committed
		// mosquitto.conf enables the error, warning and notice log types
		// only, so the broker's "mosquitto version ... starting" banner —
		// an informational line — never reaches the log.
		testcontainers.WithWaitStrategyAndDeadline(startupTimeout,
			wait.ForListeningPort(MosquittoPort),
		),
	}
	if env := passwordOverrides(cfgDir); len(env) != 0 {
		options = append(options, testcontainers.WithEnv(env))
	}
	if _, committed := MosquittoConfigDir(); committed {
		options = append(options, testcontainers.WithEntrypoint(containerEntrypoint))
	}

	container, err := testcontainers.Run(ctx, MosquittoImage, options...)
	testcontainers.CleanupContainer(t, container)
	if err != nil {
		t.Fatalf("testutil: starting %s: %v", MosquittoImage, err)
	}

	broker := &MosquittoContainer{Container: container, ConfigDir: cfgDir}
	broker.readEndpoint(t)
	return broker
}

// Address returns the broker's host and port without a scheme, which is what
// a forwarder in front of it dials.
func (m *MosquittoContainer) Address(t testing.TB) string {
	t.Helper()

	address, err := m.Container.PortEndpoint(context.Background(), MosquittoPort, "")
	if err != nil {
		t.Fatalf("testutil: reading the mapped broker port: %v", err)
	}
	return address
}

// Stop stops the broker. Its retained store goes with it: the committed
// configuration turns persistence off.
func (m *MosquittoContainer) Stop(t testing.TB) {
	t.Helper()

	timeout := stopTimeout
	if err := m.Container.Stop(context.Background(), &timeout); err != nil {
		t.Fatalf("testutil: stopping the broker: %v", err)
	}
}

// Start brings the broker back and updates URL with the port Docker
// published this time.
func (m *MosquittoContainer) Start(t testing.TB) {
	t.Helper()

	if err := m.Container.Start(context.Background()); err != nil {
		t.Fatalf("testutil: starting the broker again: %v", err)
	}
	m.readEndpoint(t)
}

// readEndpoint refreshes URL from the container's current port mapping.
func (m *MosquittoContainer) readEndpoint(t testing.TB) {
	t.Helper()

	endpoint, err := m.Container.PortEndpoint(context.Background(), MosquittoPort, "mqtt")
	if err != nil {
		t.Fatalf("testutil: reading the mapped broker port: %v", err)
	}
	m.URL = endpoint
}

// mosquittoFiles returns the configuration directory in use and the files to
// copy into the container.
func mosquittoFiles(t testing.TB) (string, []testcontainers.ContainerFile) {
	t.Helper()

	dir, committed := MosquittoConfigDir()
	if !committed {
		dir = t.TempDir()
		path := filepath.Join(dir, "mosquitto.conf")
		if err := os.WriteFile(path, []byte(minimalConfig), 0o600); err != nil {
			t.Fatalf("testutil: writing the fallback broker configuration: %v", err)
		}
		return dir, []testcontainers.ContainerFile{
			{HostFilePath: path, ContainerFilePath: containerConfigDir + "/mosquitto.conf", FileMode: 0o644},
		}
	}

	// Mosquitto 2.0.22 warns about a world-readable acl or password file, so
	// both go in at 0600 like the image build does; the image's own entrypoint
	// chowns /mosquitto before the broker drops privileges.
	return dir, []testcontainers.ContainerFile{
		{HostFilePath: filepath.Join(dir, "mosquitto.conf"), ContainerFilePath: containerConfigDir + "/mosquitto.conf", FileMode: 0o644},
		{HostFilePath: filepath.Join(dir, "acl"), ContainerFilePath: containerConfigDir + "/acl", FileMode: 0o600},
		{HostFilePath: filepath.Join(dir, "passwd.txt"), ContainerFilePath: containerConfigDir + "/passwd.txt", FileMode: 0o600},
		{HostFilePath: filepath.Join(dir, "entrypoint.sh"), ContainerFilePath: containerEntrypoint, FileMode: 0o755},
	}
}

// passwordOverrides forwards the MQTT_<USER>_PASSWORD variables that are set
// in this process, so a test run with overridden passwords reaches a broker
// that expects them. Nothing is logged: the values only travel to the
// container's environment.
func passwordOverrides(cfgDir string) map[string]string {
	raw, err := os.ReadFile(filepath.Join(cfgDir, "passwd.txt"))
	if err != nil {
		return nil
	}

	env := map[string]string{}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		user, _, found := strings.Cut(line, ":")
		if !found {
			continue
		}
		variable := "MQTT_" + strings.ToUpper(strings.ReplaceAll(user, "-", "_")) + "_PASSWORD"
		if value := os.Getenv(variable); value != "" {
			env[variable] = value
		}
	}
	return env
}

// requireDocker skips the test when no Docker daemon answers, which is the
// normal state of a machine that only runs the offline suite.
func requireDocker(t testing.TB) {
	t.Helper()

	provider, err := testcontainers.NewDockerProvider()
	if err != nil {
		t.Skipf("testutil: no Docker provider: %v", err)
	}
	defer func() { _ = provider.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := provider.Health(ctx); err != nil {
		t.Skipf("testutil: Docker is not available: %v", err)
	}
}

// randomSuffix keeps container names unique, so parallel test runs and parallel
// packages never collide on one.
func randomSuffix(t testing.TB) string {
	t.Helper()

	buf := make([]byte, 6)
	if _, err := rand.Read(buf); err != nil {
		t.Fatalf("testutil: generating a container name suffix: %v", err)
	}
	return hex.EncodeToString(buf)
}
