// Code generated by @fdp/contracts generate from manual/spec/signals.yaml and alarms.yaml. DO NOT EDIT.
// SPDX-FileCopyrightText: 2026 Meddle S.r.l.
// SPDX-License-Identifier: Apache-2.0
//
// Shape: the register map of docs/simulation.md, plus the Trigger fields the
// manual's alarm grammar needs.
// Register addresses are hand-written in layout.go; this file carries no address.

package regmap

// MapMajor changes when a scale changes or a signal is removed; a gateway
// refuses a device whose major differs from its own.
const MapMajor uint16 = 1

// MapMinor changes when a signal is added in the slot's reserved area.
const MapMinor uint16 = 0

// Provisional is true while the map was generated from the fallback fixture
// under packages/contracts/test/fixtures/manual-spec rather than from
// manual/spec.
const Provisional bool = false

// Kind distinguishes the two register encodings of a slot field.
type Kind uint8

// The signal kinds.
const (
	KindAnalog  Kind = 1
	KindDigital Kind = 2
)

// Signal is one slot field. Offset is the register offset inside the slot
// (7..13 analog in signals.yaml order, 14..21 digital in signals.yaml order,
// 22 the ambient extra).
type Signal struct {
	Tag    string  // signals.yaml id; the key of telemetry `values`
	Column string  // MetroPT-3 CSV column (verbatim, e.g. "DV_eletric"); "" for synthetic extras
	Kind   Kind    //
	Unit   string  // "bar", "degC", "A"; "" for digitals
	Scale  float64 // register = round(value*Scale) as int16; 1 for digitals
	Offset uint16  //
}

// Signals lists the slot fields in register order: 7 analog, 8 digital, then
// the synthetic extra.
var Signals = []Signal{
	{Tag: "discharge_pressure", Column: "TP2", Kind: KindAnalog, Unit: "bar", Scale: 1000, Offset: 7},
	{Tag: "line_pressure", Column: "TP3", Kind: KindAnalog, Unit: "bar", Scale: 1000, Offset: 8},
	{Tag: "separator_discharge_pressure", Column: "H1", Kind: KindAnalog, Unit: "bar", Scale: 1000, Offset: 9},
	{Tag: "dryer_purge_pressure", Column: "DV_pressure", Kind: KindAnalog, Unit: "bar", Scale: 1000, Offset: 10},
	{Tag: "reservoir_pressure", Column: "Reservoirs", Kind: KindAnalog, Unit: "bar", Scale: 1000, Offset: 11},
	{Tag: "oil_temperature", Column: "Oil_temperature", Kind: KindAnalog, Unit: "degC", Scale: 100, Offset: 12},
	{Tag: "motor_current", Column: "Motor_current", Kind: KindAnalog, Unit: "A", Scale: 100, Offset: 13},
	{Tag: "intake_closed", Column: "COMP", Kind: KindDigital, Unit: "", Scale: 1, Offset: 14},
	{Tag: "load_valve", Column: "DV_eletric", Kind: KindDigital, Unit: "", Scale: 1, Offset: 15},
	{Tag: "dryer_tower", Column: "Towers", Kind: KindDigital, Unit: "", Scale: 1, Offset: 16},
	{Tag: "regulator_contact", Column: "MPG", Kind: KindDigital, Unit: "", Scale: 1, Offset: 17},
	{Tag: "low_pressure_switch", Column: "LPS", Kind: KindDigital, Unit: "", Scale: 1, Offset: 18},
	{Tag: "purge_switch", Column: "Pressure_switch", Kind: KindDigital, Unit: "", Scale: 1, Offset: 19},
	{Tag: "oil_level_ok", Column: "Oil_level", Kind: KindDigital, Unit: "", Scale: 1, Offset: 20},
	{Tag: "flow_pulse", Column: "Caudal_impulses", Kind: KindDigital, Unit: "", Scale: 1, Offset: 21},
	{Tag: "ambient_temperature", Column: "", Kind: KindAnalog, Unit: "degC", Scale: 100, Offset: 22},
}

// Trigger is the CTRL-7 evaluation rule of an alarm (docs/simulation.md,
// "Controller alarms"). The fields below the DelayS group extend the plain
// threshold rule: they come from the manual's trigger grammar, and
// internal/ctrl7 implements every Kind.
type Trigger struct {
	Kind       string  // "threshold" | "digital" | "state_duration" | "differential" | "derived" | "composite"
	Signal     string  // tag (threshold, digital, differential A)
	SignalB    string  // tag (differential B)
	Op         string  // "gt" | "lt"
	Threshold  float64 //
	Value      bool    // digital: active when signal == Value
	Hysteresis float64 // reset band for threshold/differential
	DelayS     int     // condition must hold for DelayS seconds of sim time before the bit is set
	State      string  // state_duration: "loaded" | "unloaded" | "off"
	DurationS  int     // state_duration
	When       string  // the manual's trigger state verbatim: "any" | "loaded" | "unloaded" | "off" | "running"
	StartMaskS int     // motor-start mask: the condition is ignored for this many seconds after a start
	Abs        bool    // differential on the absolute difference
	Derived    string  // derived signal id the condition referenced ("" for a plain tag)
	ResetMode  string  // "auto" | "auto_hysteresis" | "manual" | "manual_service"
	Note       string  // free-text provenance from the generator
	All        []Trigger
	Any        []Trigger
}

// Alarm is one CTRL-7 message that the simulator evaluates into alarm_bits.
type Alarm struct {
	Code    string // e.g. "W104"
	Bit     uint8  // 0..31, unique
	Type    string // "warning" | "shutdown_warning" | "shutdown" | "service"
	Trigger Trigger
}

// Alarms lists the evaluated messages in ascending bit order.
var Alarms = []Alarm{
	{Code: "W101", Bit: 0, Type: "warning", Trigger: Trigger{Kind: "digital", Signal: "low_pressure_switch", Threshold: 1, Value: true, DelayS: 10, When: "any", ResetMode: "auto"}},
	{Code: "W102", Bit: 1, Type: "warning", Trigger: Trigger{Kind: "state_duration", Op: "gt", State: "loaded", DurationS: 600, When: "loaded", Derived: "continuous_load_time", ResetMode: "auto"}},
	{Code: "W103", Bit: 2, Type: "warning", Trigger: Trigger{Kind: "threshold", Signal: "dryer_purge_pressure", Op: "gt", Threshold: 0.5, Hysteresis: 0.1, DelayS: 60, When: "loaded", ResetMode: "auto_hysteresis"}},
	{Code: "W104", Bit: 3, Type: "warning", Trigger: Trigger{Kind: "threshold", Signal: "oil_temperature", Op: "gt", Threshold: 75, Hysteresis: 5, DelayS: 300, When: "running", ResetMode: "auto_hysteresis"}},
	{Code: "W105", Bit: 4, Type: "warning", Trigger: Trigger{Kind: "threshold", Signal: "oil_temperature", Op: "lt", Threshold: 5, DelayS: 60, When: "any", ResetMode: "auto"}},
	{Code: "W106", Bit: 5, Type: "warning", Trigger: Trigger{Kind: "threshold", Signal: "motor_current", Op: "gt", Threshold: 7.5, DelayS: 60, When: "loaded", StartMaskS: 15, ResetMode: "auto"}},
	{Code: "W107", Bit: 6, Type: "warning", Trigger: Trigger{Kind: "threshold", Signal: "motor_current", Op: "lt", Threshold: 5, DelayS: 60, When: "loaded", StartMaskS: 15, ResetMode: "auto"}},
	{Code: "W108", Bit: 7, Type: "warning", Trigger: Trigger{Kind: "derived", Op: "gt", Threshold: 6, When: "any", Derived: "motor_starts_per_hour", ResetMode: "auto", Note: "events_per_window quantity motor_starts_per_hour"}},
	{Code: "W109", Bit: 8, Type: "warning", Trigger: Trigger{Kind: "threshold", Signal: "ambient_temperature", Op: "gt", Threshold: 40, DelayS: 600, When: "any", ResetMode: "auto"}},
	{Code: "W110", Bit: 9, Type: "warning", Trigger: Trigger{Kind: "threshold", Signal: "ambient_temperature", Op: "lt", Threshold: 2, DelayS: 600, When: "any", ResetMode: "auto"}},
	{Code: "W111", Bit: 10, Type: "warning", Trigger: Trigger{Kind: "derived", Op: "gt", Threshold: 180, When: "loaded", Derived: "seconds_since_tower_change", ResetMode: "auto", Note: "seconds_since_change quantity seconds_since_tower_change"}},
	{Code: "W112", Bit: 11, Type: "warning", Trigger: Trigger{Kind: "threshold", Signal: "separator_discharge_pressure", Op: "gt", Threshold: 0.5, DelayS: 60, When: "loaded", ResetMode: "auto"}},
	{Code: "W113", Bit: 12, Type: "warning", Trigger: Trigger{Kind: "differential", Signal: "reservoir_pressure", SignalB: "line_pressure", Op: "gt", Threshold: 0.5, DelayS: 60, When: "any", Abs: true, Derived: "reservoir_line_delta", ResetMode: "auto"}},
	{Code: "W114", Bit: 13, Type: "warning", Trigger: Trigger{Kind: "digital", Signal: "flow_pulse", DelayS: 120, When: "loaded", ResetMode: "auto"}},
	{Code: "W115", Bit: 14, Type: "warning", Trigger: Trigger{Kind: "digital", Signal: "purge_switch", DelayS: 120, When: "loaded", ResetMode: "auto"}},
	{Code: "W116", Bit: 15, Type: "warning", Trigger: Trigger{Kind: "digital", Signal: "oil_level_ok", DelayS: 300, When: "any", ResetMode: "auto"}},
	{Code: "W117", Bit: 16, Type: "warning", Trigger: Trigger{Kind: "differential", Signal: "discharge_pressure", SignalB: "line_pressure", Op: "gt", Threshold: 1, DelayS: 60, When: "loaded", Derived: "discharge_line_delta", ResetMode: "auto"}},
	{Code: "X201", Bit: 17, Type: "shutdown_warning", Trigger: Trigger{Kind: "threshold", Signal: "oil_temperature", Op: "gt", Threshold: 85, DelayS: 30, When: "running", ResetMode: "auto"}},
	{Code: "X202", Bit: 18, Type: "shutdown_warning", Trigger: Trigger{Kind: "threshold", Signal: "discharge_pressure", Op: "gt", Threshold: 11, DelayS: 10, When: "any", ResetMode: "auto"}},
	{Code: "X203", Bit: 19, Type: "shutdown_warning", Trigger: Trigger{Kind: "threshold", Signal: "motor_current", Op: "gt", Threshold: 8.5, DelayS: 30, When: "loaded", StartMaskS: 15, ResetMode: "auto"}},
	{Code: "X204", Bit: 20, Type: "shutdown_warning", Trigger: Trigger{Kind: "threshold", Signal: "line_pressure", Op: "gt", Threshold: 10.5, DelayS: 30, When: "loaded", ResetMode: "auto"}},
	{Code: "S301", Bit: 21, Type: "shutdown", Trigger: Trigger{Kind: "threshold", Signal: "oil_temperature", Op: "gt", Threshold: 95, DelayS: 5, When: "running", ResetMode: "manual"}},
	{Code: "S302", Bit: 22, Type: "shutdown", Trigger: Trigger{Kind: "threshold", Signal: "discharge_pressure", Op: "gt", Threshold: 11.5, DelayS: 5, When: "any", ResetMode: "manual"}},
	{Code: "S303", Bit: 23, Type: "shutdown", Trigger: Trigger{Kind: "threshold", Signal: "motor_current", Op: "gt", Threshold: 9.5, DelayS: 5, When: "loaded", StartMaskS: 15, ResetMode: "manual"}},
	{Code: "S304", Bit: 24, Type: "shutdown", Trigger: Trigger{Kind: "composite", DelayS: 20, When: "any", ResetMode: "manual", Note: "all of 2 conditions", All: []Trigger{{Kind: "digital", Signal: "load_valve", Threshold: 1, Value: true}, {Kind: "threshold", Signal: "motor_current", Op: "lt", Threshold: 1}}}},
	{Code: "S305", Bit: 25, Type: "shutdown", Trigger: Trigger{Kind: "composite", DelayS: 10, When: "any", ResetMode: "manual", Note: "any of 2 conditions", Any: []Trigger{{Kind: "threshold", Signal: "line_pressure", Op: "lt", Threshold: -0.5}, {Kind: "threshold", Signal: "line_pressure", Op: "gt", Threshold: 15.5}}}},
	{Code: "S306", Bit: 26, Type: "shutdown", Trigger: Trigger{Kind: "composite", DelayS: 10, When: "any", ResetMode: "manual", Note: "any of 2 conditions", Any: []Trigger{{Kind: "threshold", Signal: "oil_temperature", Op: "lt", Threshold: -15}, {Kind: "threshold", Signal: "oil_temperature", Op: "gt", Threshold: 115}}}},
}
